import { Locations } from './model/data/constants.js'
import { Controller } from './controller/controller.js';

// const digimonds = [
//     "Koromon",
//     "Tsunomon",
//     "Poyomon",
//     "Tokomon",
//     "Tanemon",
//     "Pagumon",
//     "Kapurimon",
//     "Kuramon",
//     "Puttomon",
//     "Chicomon",
//     "Dorimon",
//     "Culumon",
//     "Agumon",
//     "Veemon",
//     "Guilmon",
//     "Dorumon",
//     "Betamon",
//     "Gabumon",
//     "Patamon",
//     "Piyomon",
//     "Palmon",
//     "Tentomon",
//     "Gotsumon",
//     "Otamamon",
//     "Gomamon",
//     "Bakumon",
//     "PicoDevimon",
//     "ToyAgumon",
//     "Hagurumon",
//     "Plotmon",
//     "Wormmon",
//     "Hawkmon",
//     "Armadimon",
//     "Terriermon",
//     "Lopmon",
//     "Renamon",
//     "Impmon",
//     "Keramon",
//     "Falcomon",
//     "Penmon",
//     "Goburimon",
//     "Kumamon",
//     "Kotemon",
//     "YukiAgumon",
//     "BlackAgumon",
//     "Muchomon",
//     "Ganimon",
//     "Floramon",
//     "Gizamon",
//     "Lalamon",
//     "Aruraumon",
//     "ToyAgumon (Black)",
//     "Tsukaimon",
//     "PawnChessmon (Black)",
//     "Gaomon",
//     "DotFalcomon",
//     "Kudamon",
//     "Kamemon",
//     "Dracmon",
//     "PawnChessmon (White)",
//     "DotAgumon",
//     "Greymon",
//     "Tyrannomon",
//     "Devimon",
//     "Airdramon",
//     "Seadramon",
//     "Numemon",
//     "Kabuterimon",
//     "Angemon",
//     "Vegiemon",
//     "Ogremon",
//     "Bakemon",
//     "Sukamon",
//     "Kokatorimon",
//     "Leomon",
//     "Kuwagamon",
//     "Raremon",
//     "Gekomon",
//     "Tailmon",
//     "Wizardmon",
//     "Togemon",
//     "Guardromon",
//     "ExVeemon",
//     "Stingmon",
//     "Birdramon",
//     "Ankylomon",
//     "Gargomon",
//     "Garurumon",
//     "Growlmon",
//     "Kyubimon",
//     "Chrysallimon",
//     "Seasarmon",
//     "Evilmon",
//     "Aquilamon",
//     "Gokimon",
//     "Dinohumon",
//     "Hookmon",
//     "Grizzmon",
//     "Dorugamon",
//     "Raptordramon",
//     "Hanumon",
//     "Starmon",
//     "Kiwimon",
//     "Unimon",
//     "Sorcerymon",
//     "DarkTyrannomon",
//     "Akatorimon",
//     "PlatinumSukamon",
//     "Ikkakumon",
//     "Minotarumon",
//     "Icemon",
//     "DarkLizardmon",
//     "Flarerizamon",
//     "GeoGreymon",
//     "Gaogamon",
//     "Diatrymon",
//     "Reppamon",
//     "Sunflowmon",
//     "Gawappamon",
//     "Sangloupmon",
//     "Peckmon",
//     "Fladramon",
//     "Magnamon",
//     "Prairiemon",
//     "Kongoumon",
//     "Seahomon",
//     "Shurimon",
//     "Kenkimon",
//     "Ponchomon",
//     "MetalGreymon",
//     "Monzaemon",
//     "MetalMamemon",
//     "Andromon",
//     "Etemon",
//     "Megadramon",
//     "Piccolomon",
//     "Digitamamon",
//     "AtlurKabuterimon (Blue)",
//     "Ookuwamon",
//     "Angewomon",
//     "MegaSeadramon",
//     "Dagomon",
//     "WereGarurumon (Black)",
//     "WereGarurumon (Blue)",
//     "Vamdemon",
//     "LadyDevimon",
//     "Garudamon",
//     "Blossomon",
//     "Lillymon",
//     "AtlurKabuterimon (Red)",
//     "Cyberdramon",
//     "HolyAngemon",
//     "Paildramon",
//     "Dinobeemon",
//     "Antylamon",
//     "Arukenimon",
//     "Mummymon",
//     "MegaloGrowlmon",
//     "Rapidmon",
//     "Taomon",
//     "Parrotmon",
//     "Infermon",
//     "BlackRapidmon",
//     "Kyukimon",
//     "Dorugremon",
//     "Hangyomon",
//     "Triceramon",
//     "Deramon",
//     "Silphymon",
//     "SuperStarmon",
//     "BlackMegaloGrowlmon",
//     "Zudomon",
//     "Whamon",
//     "Mamemon",
//     "Insekimon",
//     "Gigadramon",
//     "RizeGreymon",
//     "MachGaogamon",
//     "Yatagaramon",
//     "Tyilinmon",
//     "Lilamon",
//     "Matadormon",
//     "Garbemon",
//     "HeraclesKabuterimon",
//     "SaberLeomon",
//     "MetalEtemon",
//     "MarineAngemon",
//     "GigaSeadramon",
//     "Piemon",
//     "Demon",
//     "Hououmon",
//     "Pinocchimon",
//     "Rosemon",
//     "WarGreymon",
//     "MetalGarurumon",    
//     "Mugendramon",
//     "VenomVamdemon",
//     "Omegamon",
//     "Imperialdramon (Dragon Mode)",
//     "Imperialdramon (Fighter Mode)",
//     "Imperialdramon (Paladin Mode)",
//     "Deathmon",
//     "Seraphimon",
//     "HiAndromon",
//     "Cherubimon (Zen)",
//     "Cherubimon (Aku)",
//     "Dukemon",
//     "Dukemon (Crimson Mode)",
//     "SaintGargomon",
//     "Sakuyamon",
//     "Diaboromon",
//     "Plesiomon",
//     "BelialVamdemon",
//     "Imperialdramon (Dragon Mode) (Black)",
//     "PrinceMamemon",
//     "BlackSaintGargomon",
//     "Jijimon",
//     "Babamon",
//     "Parasimon",
//     "Cannondramon",
//     "SlashAngemon",
//     "Crossmon",
//     "Dorugoramon",
//     "BanchoLeomon",
//     "Darkdramon",
//     "Deathmon (Black)",
//     "Kuzuhamon",
//     "ChaosDukemon",
//     "MetalSeadramon",
//     "Valkyrimon",
//     "Justimon",
//     "Vikemon",
//     "BlackWarGreymon",
//     "GranKuwagamon",
//     "Sleipmon",
//     "Beelzebumon",
//     "Valdurmon",
//     "Neptunemon",
//     "Chronomon (Holy Mode)"
// ]

document.addEventListener("DOMContentLoaded", () => {
    // Create the controller
    let controller = new Controller();

    document.getElementById("close-modal").addEventListener("click", controller.closeDetailedDigimonModal);

    /***************
     * Maps Data
     ***************/
    document.getElementById("maps-button").addEventListener("click", () => controller.moveToLocation(Locations.Maps));
    
    document.getElementById("town-button").addEventListener("click", () => controller.moveToLocation(Locations.Town));

    // NOTE: Need to call it as a function, since I can't directly assign private fields?
    document.getElementById("attack-button-ds").addEventListener("click", () => controller.handlePlayerAttack());

    // TODO: Rerolls the current enemy Digimon, might need tweaking in the future
    document.getElementById("flee-button-ds").addEventListener("click", controller.generateNewDigimonEncounter);

    document.getElementById("prev-area-button").addEventListener("click", () => controller.changeArea(-1));

    document.getElementById("next-area-button").addEventListener("click", () => controller.changeArea(1));
    
    // NOTE: When getting party-box here it should already have all its spawned (in Controller)
    // TODO: Re-add this when implementing the ability to digivolve
    // Array.from(document.getElementById("party-box").querySelectorAll("button")).forEach((button, index) => {
    //     button.addEventListener("click", () => controller.displayDetailedDigimonInfo(index));
    // });

    // Add the button function to select a starter
    Array.from(document.getElementById("starter-selection").querySelectorAll("button")).forEach((button, index) => {
        button.addEventListener("click", () => controller.assignStarter(index));
    });
});
